<h1>Wachtwoord vergeten</h1>
<?php if ($this->successMessage): ?>
<p><?php echo $this->escape($this->successMessage) ?></p>
<?php else: ?>
<form method="post" action="<?php echo $this->url(array(), 'forgot_password') ?>">
	<p>Vul je e-mailadres in om je wachtwoord te kunnen resetten.</p>

    <label for="email-field">E-mail</label>
    <input type="email" name="email" id="email-field" required value="<?php echo $this->escape($this->email) ?>">

    <?php if ($this->formError): ?>
    <p class="error"><?php echo $this->escape($this->formError) ?></p>
    <?php endif ?>
    <button type="submit">Submit</button>
</form>
<?php endif; ?>
