<h1>Inloggen</h1>
<form method="post" action="<?php echo $this->baseUrl('/g/auth/login/process/passwordless') ?>" class="auth-form">
<?php
if ($this->errors):
	foreach ($this->errors as $error):
		echo '<p class="error">'.$this->escape($this->translate($error)).'</p>';
	endforeach;
endif;
?>
	<p>Bij ons log je in zonder wachtwoord. Vul je e-mailadres in en je krijgt een login link in je inbox.</p>

	<div class="clearfix">
		<label for="emailField" class="for-text">E-mailadres:</label>
		<input autofocus type="email" name="email" id="emailField" class="text">
	</div>

	<button type="submit">Log in</button>
</form>
