<h1>Inloggen</h1>
<form method="post" action="<?php echo $this->baseUrl('/g/auth/login/process/passwordless') ?>" class="auth-form">
<?php
if ($this->errors):
	foreach ($this->errors as $error):
		echo '<p class="error">'.$this->escape($this->translate($error)).'</p>';
	endforeach;
endif;
?>
	<p>This website uses passwordless login. Just enter your email address and you'll receive a login link directly in your inbox.</p>

	<div class="clearfix">
		<label for="emailField" class="for-text">Email address:</label>
		<input autofocus type="email" name="email" id="emailField" class="text">
	</div>

	<button type="submit">Sign in</button>
</form>
