<h1>Reset password</h1>
<?php if ($this->successMessage): ?>
<p><?php echo $this->escape($this->successMessage) ?></p>
<?php elseif ($this->error): ?>
<p class="error"><?php echo $this->escape($this->error) ?></p>
<?php else: ?>
<form method="post" action="">
    <label for="password-field">New password</label>
    <input type="password" name="password" id="password-field" required>

    <?php if ($this->formError): ?>
    <p class="error"><?php echo $this->escape($this->formError) ?></p>
    <?php endif ?>
    <button type="submit">Submit</button>
</form>
<?php endif; ?>
