language: php
php:
    - '5.3'

script:
    - composer test
    - if [ "$(git diff --diff-filter=ACMR --name-only HEAD^..HEAD -- '*.php')" != "" ]; then ./vendor/bin/phpcs --standard=vendor/grrr-amsterdam/garp3/phpcs.xml --colors --encoding=utf-8 -n -p $(git diff --diff-filter=ACMR --name-only HEAD^..HEAD -- '*.php'); fi

before_install:
    - mysql -e "create database IF NOT EXISTS garpscaffold_t;" -uroot
    - mysql -e "create user garp_development@localhost identified by 'welovegarp';" -uroot
    - mysql -e "grant all privileges on *.* to garp_development@localhost;" -uroot
    - composer install
    - php vendor/grrr-amsterdam/garp3/scripts/garp.php spawn -b --e=testing
    - php vendor/grrr-amsterdam/garp3/scripts/garp.php snippet create --e=testing

before_script:
    - chmod +x vendor/bin/phpunit
    - chmod +x vendor/bin/g

notifications:
    email: false
    slack:
        rooms:
            - secure: h9R+NUBeVXZfJ37cbdX72/ICIYS8mXMS2WR8DGDsTCx+mT6cru+D1UvnorXpOcPkv8FdX6aDHfK8LjsAT1a3IgcImRwVW4kdC7hq4L/NNlNNnTTchE/5+N6JqNY9nxrNweivMu/yuG/UzMVPLu5F1pyP3D26WGBelS3Y4eV+SgU=
        on_success: change
        on_failure: always
        template: "<%{build_url}|%{repository_name} [%{branch}] #%{build_number}>:\n%{message} (in %{duration})\nBy: %{author}\n<%{compare_url}|%{commit_message}>"
