<div style="z-index: 999; position: fixed; top: 0; left: 0; width: 100%; background: #f00; padding: 20px; color: #fff;">
	<h2 style="float: left; margin: 0 30px 0 0;">Warning!</h2> 
	<p style="margin-bottom: 0; font-size: 15px; line-height: 1.5">Modernizr was not included because it does not exist.<br>
	Please run <code style="background: #f55; padding: 5px;">gulp modernizr</code> to build it.</p>
</div>
