<script>
Ext.ns('Garp');
Ext.ns('Garp.dataTypes');
</script>
<script src="<?php echo $this->assetUrl('/js/models/base/BaseModels.min.js') ?>"></script>
<?php
if (isset($this->config()->cms->minifiedAssets) && $this->config()->cms->minifiedAssets):
	echo $this->script()->src($this->config()->assets->js->build . '/extended-models.js', true, array('crossorigin' => 'anonymous'));
else:
?>
<!-- BEGIN SPAWNED CALLS -->
<script crossorigin="anonymous" src="<?php echo $this->assetUrl('/js/garp/models/AuthLocal.js') ?>"></script>
<script crossorigin="anonymous" src="<?php echo $this->assetUrl('/js/models/AuthLocal.js') ?>"></script>
<script crossorigin="anonymous" src="<?php echo $this->assetUrl('/js/garp/models/AuthPasswordless.js') ?>"></script>
<script crossorigin="anonymous" src="<?php echo $this->assetUrl('/js/models/AuthPasswordless.js') ?>"></script>
<script crossorigin="anonymous" src="<?php echo $this->assetUrl('/js/garp/models/ClusterClearCacheJob.js') ?>"></script>
<script crossorigin="anonymous" src="<?php echo $this->assetUrl('/js/models/ClusterClearCacheJob.js') ?>"></script>
<script crossorigin="anonymous" src="<?php echo $this->assetUrl('/js/garp/models/ClusterRecurringJob.js') ?>"></script>
<script crossorigin="anonymous" src="<?php echo $this->assetUrl('/js/models/ClusterRecurringJob.js') ?>"></script>
<script crossorigin="anonymous" src="<?php echo $this->assetUrl('/js/garp/models/ClusterServer.js') ?>"></script>
<script crossorigin="anonymous" src="<?php echo $this->assetUrl('/js/models/ClusterServer.js') ?>"></script>
<script crossorigin="anonymous" src="<?php echo $this->assetUrl('/js/models/Event.js') ?>"></script>
<script crossorigin="anonymous" src="<?php echo $this->assetUrl('/js/garp/models/Image.js') ?>"></script>
<script crossorigin="anonymous" src="<?php echo $this->assetUrl('/js/models/Image.js') ?>"></script>
<script crossorigin="anonymous" src="<?php echo $this->assetUrl('/js/models/Musician.js') ?>"></script>
<script crossorigin="anonymous" src="<?php echo $this->assetUrl('/js/models/News.js') ?>"></script>
<script crossorigin="anonymous" src="<?php echo $this->assetUrl('/js/models/Piece.js') ?>"></script>
<script crossorigin="anonymous" src="<?php echo $this->assetUrl('/js/garp/models/ScheduledJob.js') ?>"></script>
<script crossorigin="anonymous" src="<?php echo $this->assetUrl('/js/models/ScheduledJob.js') ?>"></script>
<script crossorigin="anonymous" src="<?php echo $this->assetUrl('/js/garp/models/Snippet.js') ?>"></script>
<script crossorigin="anonymous" src="<?php echo $this->assetUrl('/js/models/Snippet.js') ?>"></script>
<script crossorigin="anonymous" src="<?php echo $this->assetUrl('/js/garp/models/User.js') ?>"></script>
<script crossorigin="anonymous" src="<?php echo $this->assetUrl('/js/models/User.js') ?>"></script>
<script crossorigin="anonymous" src="<?php echo $this->assetUrl('/js/garp/models/Video.js') ?>"></script>
<script crossorigin="anonymous" src="<?php echo $this->assetUrl('/js/models/Video.js') ?>"></script>

<!-- END SPAWNED CALLS -->
<?php
endif;
?>
<script>
Ext.onReady(function(){
	Garp.modelMenu = new Garp.ModelMenu({
		menuItems: [
			'Snippet',
			'Image',
			'-',
			'AuthPasswordless',
			'User'
		]
	});
});
</script>
